CREATE TYPE "status" AS ENUM (
  'running',
  'done',
  'failure'
);

CREATE TYPE "media_type" AS ENUM (
  'a',
  'v'
);

CREATE TABLE "origin" (
  "id" varchar PRIMARY KEY,
  "title" varchar,
  "duration" int,
  "info_status" status NOT NULL DEFAULT 'running'
);

CREATE TABLE "media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vid" varchar NOT NULL,
  "type" media_type NOT NULL,
  "media_status" status NOT NULL DEFAULT 'running',
  "access_key" char(16) NOT NULL,
  "recently_access_time" timestamp NOT NULL DEFAULT (now())
);