GET https://e3.nycu.edu.tw/pluginfile.php/1734426/mod_assign/introattachment/0/HW2.pdf HTTP/1.1
Cookie: e3.nycu.edu.tw	MoodleSession=4uqmbcie4vee4lqbu3jto32tvv; Expires=null; Path=/; Secure; HttpOnly; Domain=e3.nycu.edu.tw	